version: "2"
services:
    worker:
        build: ./worker
        ports:
            - "5000:5000"
        volumes:
            - .:/worker
        environment:
            - LC_ALL=C.UTF-8
            - LANG=C.UTF-8
